version: '3'
services:
  mongo:
    image: mongo:4
    volumes:
      - ./db:/data/db
  genieacs-cwmp:
    command: /genieacs/dist/bin/genieacs-cwmp
    image: genieacs
    ports:
      - 7547:7547
    volumes:
      - ./config:/genieacs/config
  genieacs-nbi:
    command: /genieacs/dist/bin/genieacs-nbi
    image: genieacs
    ports:
      - 7557:7557
    volumes:
      - ./config:/genieacs/config
  genieacs-ui:
    command: /genieacs/dist/bin/genieacs-ui
    image: genieacs
    ports:
      - 3000:3000
    volumes:
      - ./config:/genieacs/config
  mongo-express: 
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
